services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "9080:9080"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
